/**
 * Tecan EVO150 .gwl (Gemini Worklist) generator.
 * EVOware Standard 2.8 — worklists loaded via Scripts → Run Worklist.
 *
 * GWL format: semicolon-delimited
 *   A;rack;pos;vol;;;   — Aspirate
 *   D;rack;pos;vol;;;   — Dispense
 *   W;                  — Wash
 *   C;comment           — Comment
 *   B;                  — Break (pause)
 *
 * Well positions: column-major numbering
 *   96-well: A1=1, B1=2, ..., H1=8, A2=9, ..., H12=96
 *   48-well: A1=1, B1=2, ..., H1=8, A2=9, ..., H6=48
 */

import { ROWS_96 } from "./geometry";

// ── Default deck config (user can override) ──
const DEFAULT_CONFIG = {
  source96Rack: "Source96",
  dest96Rack: "Dest96",
  dest48Rack: "Dest48",
  petriRack: "Petri",
  washStation: true,
  aspirateVol: 5,       // µL for passage
  dispenseVol: 5,       // µL for passage
  transferVol: 10,      // µL per replicate for 96→48
  tipChangeMode: "always", // "always" | "between_clones" | "never"
};

function wellToPos(well) {
  const row = well.charCodeAt(0) - 65;
  const col = parseInt(well.slice(1)) - 1;
  return col * 8 + row + 1;
}

function header(comment, config) {
  return [
    `C;${comment}`,
    `C;Generated by CloneTracker`,
    `C;Date: ${new Date().toISOString().split("T")[0]}`,
    `C;Deck: source=${config.source96Rack}, dest96=${config.dest96Rack}, dest48=${config.dest48Rack}`,
    `C;Volumes: aspirate=${config.aspirateVol}uL, dispense=${config.dispenseVol}uL, transfer=${config.transferVol}uL`,
    "",
  ];
}

function washCmd(config) {
  return config.washStation ? ["W;"] : [];
}

/**
 * Get stored Tecan config from localStorage
 */
export function getTecanConfig() {
  try {
    const stored = localStorage.getItem("ct-tecan-config");
    if (stored) return { ...DEFAULT_CONFIG, ...JSON.parse(stored) };
  } catch {}
  return { ...DEFAULT_CONFIG };
}

/**
 * Save Tecan config to localStorage
 */
export function saveTecanConfig(config) {
  localStorage.setItem("ct-tecan-config", JSON.stringify(config));
}

/**
 * MODE 1: Picking from petri dish to 96-well
 * Used when Tecan does the picking (robot with colony picker).
 */
export function generatePickingGwl(colonies, config = null) {
  const cfg = config || getTecanConfig();
  const lines = header(`Picking: Petri → ${cfg.source96Rack}`, cfg);

  for (const col of colonies) {
    const destPos = wellToPos(col.well);
    lines.push(`C;Colony at ${col.well}`);
    lines.push(`A;${cfg.petriRack};1;${cfg.aspirateVol};;;`);
    lines.push(`D;${cfg.source96Rack};${destPos};${cfg.dispenseVol};;;`);
    if (cfg.tipChangeMode === "always") lines.push(...washCmd(cfg));
  }

  return lines.join("\r\n");
}

/**
 * MODE 2: 96→96 passage (stamp/replicate)
 */
export function generatePassageGwl(sourcePlate, destPlateName, config = null) {
  const cfg = config || getTecanConfig();
  const lines = header(`Passage: ${sourcePlate.name} → ${destPlateName}`, cfg);

  for (const [well, data] of Object.entries(sourcePlate.wells)) {
    if (data.status === "picked" || data.status === "control-wt") {
      const pos = wellToPos(well);
      lines.push(`A;${cfg.source96Rack};${pos};${cfg.aspirateVol};;;`);
      lines.push(`D;${cfg.dest96Rack};${pos};${cfg.dispenseVol};;;`);
      if (cfg.tipChangeMode !== "never") lines.push(...washCmd(cfg));
    }
  }

  return lines.join("\r\n");
}

/**
 * MODE 3: 96→48-DWP transfer with replicates
 */
export function generateTransfer96to48Gwl(sourcePlateName, culturePlates, config = null) {
  const cfg = config || getTecanConfig();
  const lines = header(`Transfer: ${sourcePlateName} → ${culturePlates.length} × 48-DWP`, cfg);

  for (let pi = 0; pi < culturePlates.length; pi++) {
    const cp = culturePlates[pi];
    lines.push(`C;--- Plate ${cp.name} ---`);
    if (pi > 0) lines.push("B;"); // Break between plates (operator swaps plate)

    const seen = new Set();
    for (const [well, data] of Object.entries(cp.wells)) {
      if (data.status === "picked" && data.cloneId && data.cloneId !== "WT" && !seen.has(data.cloneId)) {
        seen.add(data.cloneId);
        // Find all replicate wells for this clone
        const destWells = Object.entries(cp.wells)
          .filter(([, w]) => w.cloneId === data.cloneId)
          .map(([w]) => w);
        const srcPos = wellToPos(data.sourceWell || "A1");

        lines.push(`C;Clone ${data.cloneId} (${data.sourceWell}) → ${destWells.join(",")}`);
        for (const dw of destWells) {
          const destPos = wellToPos(dw);
          lines.push(`A;${cfg.source96Rack};${srcPos};${cfg.transferVol};;;`);
          lines.push(`D;${cfg.dest48Rack};${destPos};${cfg.transferVol};;;`);
        }
        if (cfg.tipChangeMode !== "never") lines.push(...washCmd(cfg));
      }
    }

    // WT control
    const wtWells = Object.entries(cp.wells)
      .filter(([, w]) => w.status === "control-wt")
      .map(([w]) => w);
    if (wtWells.length > 0) {
      lines.push(`C;WT control → ${wtWells.join(",")}`);
      for (const dw of wtWells) {
        const destPos = wellToPos(dw);
        lines.push(`A;${cfg.source96Rack};1;${cfg.transferVol};;;`);
        lines.push(`D;${cfg.dest48Rack};${destPos};${cfg.transferVol};;;`);
      }
      lines.push(...washCmd(cfg));
    }
  }

  return lines.join("\r\n");
}

/**
 * MODE 4: Full pipeline — picking + passage + transfer in one worklist
 */
export function generateFullPipelineGwl(colonies, sourcePlate, culturePlates, config = null) {
  const cfg = config || getTecanConfig();
  const lines = header("Full pipeline: Petri → 96-well → 48-DWP", cfg);

  // Step 1: Picking
  lines.push("C;=== STEP 1: PICKING ===");
  for (const col of colonies) {
    const destPos = wellToPos(col.well);
    lines.push(`A;${cfg.petriRack};1;${cfg.aspirateVol};;;`);
    lines.push(`D;${cfg.source96Rack};${destPos};${cfg.dispenseVol};;;`);
    if (cfg.tipChangeMode === "always") lines.push(...washCmd(cfg));
  }

  lines.push("", "B;", "C;=== Incubate, then continue ===", "B;", "");

  // Step 2: Transfer to 48-DWP
  lines.push("C;=== STEP 2: TRANSFER TO 48-DWP ===");
  const transferLines = generateTransfer96to48Gwl(sourcePlate?.name || "Source", culturePlates, cfg);
  // Skip header of transfer (already have our own)
  const transferBody = transferLines.split("\r\n").filter((l) => !l.startsWith("C;Generated") && !l.startsWith("C;Date") && !l.startsWith("C;Deck") && !l.startsWith("C;Volumes"));
  lines.push(...transferBody);

  return lines.join("\r\n");
}

/**
 * Download GWL file
 */
export function downloadGwl(content, filename) {
  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
